# Generated by Django 4.1.5 on 2024-07-20 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0002_alter_category_options_items"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="items",
            options={"verbose_name_plural": "項目"},
        ),
    ]
