# Generated by Django 4.1.5 on 2024-07-21 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0003_alter_items_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="items",
            old_name="crated_by",
            new_name="created_by",
        ),
        migrations.AlterField(
            model_name="items",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="item.category",
            ),
        ),
    ]
